// 样式对象

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    gap: '16px',
    padding: '16px',
    boxSizing: 'border-box',
  },
  main: {
    display: 'flex',
    flex: '1',
    gap: '16px',
    minHeight: 0,
  },
  voiceGridWrapper: {
    maxHeight: '240px',
    overflowY: 'auto',
    marginTop: '8px',
    paddingRight: '4px',
  },
  voiceGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '8px',
  },
  voiceItem: {
    padding: '8px 6px',
    borderRadius: '8px',
    border: '2px solid transparent',
    cursor: 'pointer',
    textAlign: 'center',
    fontSize: '12px',
    transition: 'all 0.2s',
    position: 'relative',
  },
  actionBtn: {
    position: 'absolute',
    top: '2px',
    fontSize: '13px',
    lineHeight: 1,
    cursor: 'pointer',
    fontWeight: '700',
    width: '18px',
    height: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    transition: 'opacity 0.2s',
    background: 'var(--background, #1e293b)',
    zIndex: 1,
  },
  addVoiceItem: {
    padding: '8px 6px',
    borderRadius: '8px',
    border: '2px dashed var(--border, #444)',
    cursor: 'pointer',
    textAlign: 'center',
    fontSize: '12px',
    color: 'var(--muted-foreground, #999)',
    transition: 'all 0.2s',
  },
  addForm: {
    marginTop: '8px',
    padding: '10px',
    borderRadius: '8px',
    border: '1px solid var(--border, #444)',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  controlsRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flexWrap: 'wrap',
  },
  audioPlayer: {
    width: '100%',
    height: '40px',
    borderRadius: '8px',
    outline: 'none',
  },
  audioPlayerInline: {
    flex: '1',
    minWidth: '200px',
    height: '40px',
    borderRadius: '8px',
    outline: 'none',
  },
  sliderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginTop: '4px',
    width: '100%',
  },
  sliderValue: {
    fontSize: '13px',
    fontWeight: '600',
    minWidth: '36px',
    textAlign: 'right',
  },
  charCount: {
    fontSize: '11px',
    textAlign: 'right',
    marginTop: '4px',
    opacity: 0.6,
  },
};

export default styles;
