import type { NodeTypeDefinition } from '@agent-spaces/shared';

export const utilsNodes: NodeTypeDefinition[] = [
  {
    type: 'flatten_array',
    label: 'nodes.flatten_array.label',
    category: 'nodes.categories.utilities',
    icon: 'Layers',
    description: 'nodes.flatten_array.description',
    properties: [
      {
        key: 'array',
        label: 'nodes.flatten_array.props.array.label',
        type: 'array',
        required: true,
        inputMode: 'variable',
        tooltip: 'nodes.flatten_array.props.array.tooltip',
        default: [],
        itemTemplate: [],
        fields: [],
      },
      {
        key: 'key',
        label: 'nodes.flatten_array.props.key.label',
        type: 'text',
        placeholder: 'names',
        tooltip: 'nodes.flatten_array.props.key.tooltip',
      },
    ],
    outputs: [{ key: 'result', type: 'any[]' }],
  },
  {
    type: 'pluck_array_key',
    label: 'nodes.pluck_array_key.label',
    category: 'nodes.categories.utilities',
    icon: 'ListFilter',
    description: 'nodes.pluck_array_key.description',
    properties: [
      {
        key: 'array',
        label: 'nodes.pluck_array_key.props.array.label',
        type: 'array',
        required: true,
        inputMode: 'variable',
        tooltip: 'nodes.pluck_array_key.props.array.tooltip',
        default: [],
        itemTemplate: {},
        fields: [],
      },
      {
        key: 'key',
        label: 'nodes.pluck_array_key.props.key.label',
        type: 'text',
        required: true,
        placeholder: 'name',
        tooltip: 'nodes.pluck_array_key.props.key.tooltip',
      },
    ],
    outputs: [{ key: 'result', type: 'any[]' }],
  },
  {
    type: 'array_text_replace',
    label: 'nodes.array_text_replace.label',
    category: 'nodes.categories.utilities',
    icon: 'Replace',
    description: 'nodes.array_text_replace.description',
    properties: [
      {
        key: 'array',
        label: 'nodes.array_text_replace.props.array.label',
        type: 'array',
        required: true,
        inputMode: 'variable',
        tooltip: 'nodes.array_text_replace.props.array.tooltip',
        default: [],
        itemTemplate: {},
        fields: [],
      },
      {
        key: 'findText',
        label: 'nodes.array_text_replace.props.findText.label',
        type: 'text',
        required: true,
        tooltip: 'nodes.array_text_replace.props.findText.tooltip',
      },
      {
        key: 'replaceText',
        label: 'nodes.array_text_replace.props.replaceText.label',
        type: 'text',
        required: true,
        tooltip: 'nodes.array_text_replace.props.replaceText.tooltip',
      },
      {
        key: 'replaceCount',
        label: 'nodes.array_text_replace.props.replaceCount.label',
        type: 'number',
        default: 0,
        tooltip: 'nodes.array_text_replace.props.replaceCount.tooltip',
      },
      {
        key: 'replaceMode',
        label: 'nodes.array_text_replace.props.replaceMode.label',
        type: 'select',
        default: 'literal',
        options: [
          { label: 'nodes.array_text_replace.props.replaceMode.literal', value: 'literal' },
          { label: 'nodes.array_text_replace.props.replaceMode.regex', value: 'regex' },
        ],
      },
    ],
    outputs: [{ key: 'result', type: 'string[]' }],
  },
];
